# Generated by Django 2.2.13 on 2021-02-12 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='category',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='image',
            field=models.ImageField(default=0, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='slug',
            field=models.SlugField(default=0, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='title',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0, max_length=255, null=True, verbose_name='Наименование')),
                ('slug', models.SlugField(default=0, null=True, unique=True)),
                ('image', models.ImageField(default=0, null=True, upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Цена')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ')),
                ('display_type', models.CharField(max_length=255, verbose_name='Тип дисплея')),
                ('display_resolution', models.CharField(max_length=255, verbose_name='Разрешение')),
                ('processor_name', models.CharField(max_length=255, verbose_name='Название процессора')),
                ('processor_freq', models.CharField(max_length=255, verbose_name='Частота процессора')),
                ('processor_cores', models.CharField(max_length=255, verbose_name='Кол-во ядер процессора')),
                ('Video_name', models.CharField(max_length=255, verbose_name='Название видеокарты')),
                ('accum_volume', models.CharField(max_length=255, verbose_name='объем аккумулятора')),
                ('ram', models.CharField(max_length=255, verbose_name='ОЗУ')),
                ('sd', models.BooleanField(default=True)),
                ('storage', models.CharField(max_length=255, verbose_name='Объем ПЗУ')),
                ('main_cam_mp', models.CharField(max_length=255, verbose_name='Главная камера')),
                ('frontal_cam_mp', models.CharField(max_length=255, verbose_name='Фронтальная камера')),
                ('category', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ps4Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0, max_length=255, null=True, verbose_name='Наименование')),
                ('slug', models.SlugField(default=0, null=True, unique=True)),
                ('image', models.ImageField(default=0, null=True, upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Цена')),
                ('age', models.CharField(max_length=255, verbose_name='Возрастной рейтинг')),
                ('category', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ps3Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0, max_length=255, null=True, verbose_name='Наименование')),
                ('slug', models.SlugField(default=0, null=True, unique=True)),
                ('image', models.ImageField(default=0, null=True, upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Цена')),
                ('age', models.CharField(max_length=255, verbose_name='Возрастной рейтинг')),
                ('category', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0, max_length=255, null=True, verbose_name='Наименование')),
                ('slug', models.SlugField(default=0, null=True, unique=True)),
                ('image', models.ImageField(default=0, null=True, upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Цена')),
                ('diagonal', models.CharField(max_length=255, verbose_name='Диагональ')),
                ('display_type', models.CharField(max_length=255, verbose_name='Тип дисплея')),
                ('display_resolution', models.CharField(max_length=255, verbose_name='Разрешение')),
                ('processor_name', models.CharField(max_length=255, verbose_name='Название процессора')),
                ('processor_freq', models.CharField(max_length=255, verbose_name='Частота процессора')),
                ('processor_cores', models.CharField(max_length=255, verbose_name='Кол-во ядер процессора')),
                ('ram', models.CharField(max_length=255, verbose_name='ОЗУ')),
                ('Video_name', models.CharField(max_length=255, verbose_name='Название видеокарты')),
                ('Video', models.CharField(max_length=255, verbose_name='Кол-во видеопамяти')),
                ('time_without_charge', models.CharField(max_length=255, verbose_name='Время автономности')),
                ('storage', models.CharField(max_length=255, verbose_name='Объем ПЗУ')),
                ('category', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GraphicsCardProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0, max_length=255, null=True, verbose_name='Наименование')),
                ('slug', models.SlugField(default=0, null=True, unique=True)),
                ('image', models.ImageField(default=0, null=True, upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Цена')),
                ('videoСard_name', models.CharField(max_length=255, verbose_name='Название видеокарты')),
                ('videoСard_vram_count', models.CharField(max_length=255, verbose_name='Кол-во видеопамяти')),
                ('videoСard_vram_type', models.CharField(max_length=255, verbose_name='Тип видеопамяти')),
                ('videoCard_bus', models.CharField(max_length=255, verbose_name='Разрядность Шины')),
                ('category', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0, max_length=255, null=True, verbose_name='Наименование')),
                ('slug', models.SlugField(default=0, null=True, unique=True)),
                ('image', models.ImageField(default=0, null=True, upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True, verbose_name='Цена')),
                ('gen', models.CharField(max_length=255, verbose_name='Поколение консоли')),
                ('manufacture', models.CharField(max_length=255, verbose_name='Производитель')),
                ('year', models.CharField(max_length=255, verbose_name='Год производства')),
                ('category', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
