# Generated by Django 2.2.13 on 2021-02-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210212_2138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GraphicsCardProduct',
            new_name='GraphicsCard',
        ),
    ]
